Introduce x-menu blade component
novius/laravel-nova-menu pull request #32
Opened 2023-12-13 14:36 UTC by felixgilles

2023-12-14 09:01 UTC, tonyyb requested changes

2023-12-14 09:01 UTC, tonyyb commented on README.md
> +<x-menu slug="slug-of-menu" />
`x-menu` un peu trop générique (risque de conflits) : voir pour personnaliser ça avec un namespace custom ou pour carrément donner la main pour le changer.

2023-12-14 09:01 UTC, tonyyb commented on README.md
> +<x-menu :slug="Menu::find(1)" />
Changer `:slug` pour `:menu`

2023-12-14 09:01 UTC, tonyyb commented on README.md
>  You can display menu with :
Ajouter un upgrade guide vers la version 6.0 qui explique le deprecated

2023-12-14 14:17 UTC, felixgilles commented on README.md
> +<x-menu slug="slug-of-menu" />
<x-laravel-nova-menu::menu />

2023-12-14 14:18 UTC, felixgilles commented on README.md
> +<x-menu :slug="Menu::find(1)" />
Done

2023-12-14 14:18 UTC, felixgilles commented on README.md
>  You can display menu with :
See UPGRADE.md

2024-01-16 11:15 UTC, tonyyb approved these changes

2024-01-16 11:15 UTC, merged