Add a target blank option in menu item
novius/laravel-nova-menu pull request #8
Opened 2020-02-10 11:05 UTC by alicecd

Crud boolean doesn't works on chrome, but works fine on firefox

2020-02-10 11:26 UTC, tonyyb requested changes

2020-02-10 11:26 UTC, tonyyb commented on resources/lang/en/menu.php
> +    'target_blank' => 'Target blank ?',
Open in a new tab ?

2020-02-10 11:28 UTC, alicecd commented on resources/lang/en/menu.php
> +    'target_blank' => 'Target blank ?',
All right !

2020-02-10 11:33 UTC, tonyyb commented
Resolve : https://github.com/novius/laravel-nova-menu/projects/1#card-32246504

2020-02-12 07:08 UTC, tonyyb approved these changes

2020-02-12 07:08 UTC, merged